name: completion_ft
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pip:
      - -r requirements.txt
      - mlflow==2.3.2
      - jsonargparse==4.21.1
      - peft==0.3.0